default_platform(:mac)

platform :mac do
  desc "Upload build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("APP_STORE_CONNECT_KEY_ID"),
      issuer_id: ENV.fetch("APP_STORE_CONNECT_ISSUER_ID"),
      key_content: ENV.fetch("APP_STORE_CONNECT_API_KEY"),
      is_key_content_base64: false
    )

    app_identifier = "com.sedaf.Tiempo1"

    build_number = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: app_identifier,
      platform: "osx",
      initial_build_number: 0
    ) + 1

    increment_build_number(build_number: build_number)

    build_app(
      scheme: "KeynoteCompanionMacos",
      configuration: "Release",
      export_method: "app-store",
      destination: "generic/platform=macOS",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          app_identifier => ENV.fetch("PROVISIONING_PROFILE_NAME")
        }
      },
      xcargs: [
        "CODE_SIGN_STYLE=Manual",
        "DEVELOPMENT_TEAM=FJ9UDU5R7B",
        "CODE_SIGN_IDENTITY='Apple Distribution'",
        "PROVISIONING_PROFILE='#{ENV.fetch("PROVISIONING_PROFILE_UUID")}'",
        "PROVISIONING_PROFILE_SPECIFIER='#{ENV.fetch("PROVISIONING_PROFILE_NAME")}'"
      ].join(" ")
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: app_identifier,
      skip_waiting_for_build_processing: true
    )
  end
end
